/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ispatipay;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author deuterium2h
 */
public class frmActivityLog extends javax.swing.JFrame {

    /**
     * Creates new form frmActionLog
     */
    public frmActivityLog() {
        initComponents();
        conn = Database.getConnection();
    }

    private static frmActivityLog obj = null;

    public static frmActivityLog getObj(){
        if ( obj == null ) {
            obj = new frmActivityLog();
        }

        return obj;
    }

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    static final String table = "activity_log";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgPrintForm = new javax.swing.JDialog();
        pnlSearchContainer = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        pnlTableContainer = new javax.swing.JPanel();
        scrTableScroll = new javax.swing.JScrollPane();
        tblActivityLog = new javax.swing.JTable();
        mnbActivityLog = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mniPrint = new javax.swing.JMenuItem();
        mniSepartaor1 = new javax.swing.JPopupMenu.Separator();
        mniClose = new javax.swing.JMenuItem();

        dlgPrintForm.setResizable(false);

        javax.swing.GroupLayout dlgPrintFormLayout = new javax.swing.GroupLayout(dlgPrintForm.getContentPane());
        dlgPrintForm.getContentPane().setLayout(dlgPrintFormLayout);
        dlgPrintFormLayout.setHorizontalGroup(
            dlgPrintFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        dlgPrintFormLayout.setVerticalGroup(
            dlgPrintFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlSearchContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchContainerLayout = new javax.swing.GroupLayout(pnlSearchContainer);
        pnlSearchContainer.setLayout(pnlSearchContainerLayout);
        pnlSearchContainerLayout.setHorizontalGroup(
            pnlSearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch)
                .addContainerGap())
        );
        pnlSearchContainerLayout.setVerticalGroup(
            pnlSearchContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblActivityLog.setAutoCreateRowSorter(true);
        tblActivityLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTableScroll.setViewportView(tblActivityLog);

        javax.swing.GroupLayout pnlTableContainerLayout = new javax.swing.GroupLayout(pnlTableContainer);
        pnlTableContainer.setLayout(pnlTableContainerLayout);
        pnlTableContainerLayout.setHorizontalGroup(
            pnlTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTableContainerLayout.setVerticalGroup(
            pnlTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuMenu.setText("Menu");

        mniPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mniPrint.setText("Print");
        mnuMenu.add(mniPrint);
        mnuMenu.add(mniSepartaor1);

        mniClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mniClose.setText("Close");
        mniClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCloseActionPerformed(evt);
            }
        });
        mnuMenu.add(mniClose);

        mnbActivityLog.add(mnuMenu);

        setJMenuBar(mnbActivityLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSearchContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSearchContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniCloseActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        String sql = "SELECT * FROM activity_log WHERE username LIKE ? "
                + "OR action LIKE ? OR action_time LIKE ? OR action_date LIKE ?";

        if ( Helper.isTextFieldBlank(txtSearch) ) {
            Helper.loadTable(tblActivityLog, conn, table);
        }
        else {

            String item = txtSearch.getText() + "%";

            try {
                pst = conn.prepareStatement(sql);
                for ( int i = 1; i <= 4; i++ ) {
                    pst.setString(i, item);
                }
                rs = pst.executeQuery();
                tblActivityLog.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch ( SQLException e ) {
                System.err.println(e);
            }
            finally {
                Helper.closeIfSqlite(pst, rs);
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmActivityLog().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgPrintForm;
    private javax.swing.JMenuBar mnbActivityLog;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JMenuItem mniPrint;
    private javax.swing.JPopupMenu.Separator mniSepartaor1;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JPanel pnlSearchContainer;
    private javax.swing.JPanel pnlTableContainer;
    private javax.swing.JScrollPane scrTableScroll;
    private javax.swing.JTable tblActivityLog;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
